version: "3.8"

services:
  postgres:
    container_name: thullo_postgres
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-thullo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-thullo}
      PGDATA: /data/postgres
      POSTGRES_DB: thullo
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
  postgres:
